# Generated by Django 3.0.7 on 2021-03-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ignisdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('is_liked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ignisdata',
            },
        ),
    ]
